name: snnbd
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.5.39
  - cuda-runtime=12.1.0
  - cuda-version=12.5
  - cupy=13.2.0
  - cupy-core=13.2.0
  - debugpy=1.8.9
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastrlock=0.8.2
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2022.1.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.4
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.10.1.7
  - libcurand=10.3.6.82
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libopenblas=0.3.27
  - libpng=1.6.39
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.2.1
  - numpy=2.0.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.4.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.9.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=69.5.1
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.12
  - tk=8.6.14
  - torchaudio=2.4.0
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - et-xmlfile==2.0.0
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - grpcio==1.66.1
      - imageio==2.34.2
      - importlib-metadata==8.4.0
      - importlib-resources==6.4.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markdown==3.7
      - matplotlib==3.9.1
      - openpyxl==3.1.5
      - packaging==24.1
      - pandas==2.2.2
      - protobuf==5.28.0
      - pyparsing==3.1.2
      - pytz==2024.1
      - rarfile==4.2
      - scikit-image==0.24.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - spikingjelly==0.0.0.0.14
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tifffile==2024.7.24
      - tqdm==4.66.4
      - tzdata==2024.1
      - unrar==0.4
      - werkzeug==3.0.4
      - zipp==3.19.2
